import { defineConfig, globalIgnores } from 'eslint/config';
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default defineConfig(
  // Matches the project's original lint scope (`eslint src/**/*.{ts,tsx}`): root-level config
  // files were never linted before switching the script to `eslint .` for flat-config's sake.
  // src/generated/level5-v2.ts is committed but auto-generated by openapi-typescript (issue #4)
  // and never hand-edited - excluded so neither lint nor lint-staged's `eslint --fix` reformats
  // it away from what `npm run contracts:check` expects.
  globalIgnores(['.next', 'next.config.ts', 'eslint.config.js', 'vitest.config.ts', 'vitest.setup.ts', 'next-env.d.ts', 'src/generated/**', 'playwright.config.ts', 'playwright.config.production.ts', 'e2e/**', 'e2e-production/**']),
  js.configs.recommended,
  tseslint.configs.recommended,
  react.configs.flat.recommended,
  jsxA11y.flatConfigs.recommended,
  {
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node },
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'react-hooks': reactHooks,
    },
    settings: {
      // Explicit version, not 'detect': eslint-plugin-react's auto-detection calls a context
      // API (getFilename) that ESLint 10 removed, crashing every lint run.
      react: { version: '19.2.8' },
    },
    rules: {
      ...reactHooks.configs['recommended-latest'].rules,
      // Next's error.tsx/not-found.tsx-style boundary components must accept props (error/reset)
      // the framework passes at runtime even when a given fallback doesn't use them.
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      // Next's own JSX transform doesn't require React in scope.
      'react/react-in-jsx-scope': 'off',
      'react/jsx-uses-react': 'off',
      // defaultProps on function components is deprecated (React 18.3+ warns on it) - TS optional
      // props plus a destructured default value is the modern replacement this rule doesn't know
      // about.
      'react/require-default-props': 'off',
      // Thin wrapper components (ButtonLink forwarding arbitrary MUI ButtonProps) need to spread
      // - enumerating every prop they forward would defeat the point of the wrapper.
      'react/jsx-props-no-spreading': 'off',
    },
  },
  prettier,
);
