export enum Mode {
  TotalPoints = 1,
  Total3Pointers = 2,
  Total4Pointers = 3,
  Total7Pointers = 4,
  TotalDistance = 6,
  SpotUp3s = 7,
  SpotUp4s = 8,
  SpotUpAll = 9,
  ConsecutiveShots = 14,
  InThePocket = 15,
  ThreePointContest = 16,
  FourPointContest = 17,
  AllPointContest = 18,
  PointsByDistance = 19,
  BashUpSomeNerds = 20,
  BattleRoyal = 21,
  CageMatch = 22,
  VersusCpu = 23,
  SevenPointContest = 24,
  SpotUp7s = 25,
  BeatThaComputahs = 26,
  Lockdown = 27,
  ArcadeMode = 98,
  FreePlay = 99
}
